api = "0.2"

[buildpack]
  id = "thedarkside/ruby-buildpack"
  name = "Custom Paketo Ruby Buildpack"

[metadata]
  include-files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    version = "2.3.2"

  [[order.group]]
    id = "paketo-buildpacks/mri"
    version = "0.2.3"

  [[order.group]]
    id = "paketo-buildpacks/bundler"
    version = "0.1.7"

  [[order.group]]
    id = "paketo-buildpacks/bundle-install"
    version = "0.2.2"

  [[order.group]]
    id = "paketo-buildpacks/rails-assets"
    version = "0.2.2"

  [[order.group]]
    id = "paketo-buildpacks/puma"
    version = "0.0.59"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version = "4.2.2"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    version = "3.1.1"
